In [ ]:
#Creating Tensors

import tensorflow as tf

# Scalar (0D tensor)
scalar_tensor = tf.constant(5)
print(scalar_tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# Vector (1D tensor)
vector_tensor = tf.constant([1, 2, 3, 4])
print(vector_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
# Matrix (2D tensor)
matrix_tensor = tf.constant([[1, 2], [3, 4]])
print(matrix_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
# Tensor of zeros (2D tensor)
zeros_tensor = tf.zeros([3, 3])
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
# Tensor of ones (2D tensor)
ones_tensor = tf.ones([2, 2])
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
#Tensor Operation

import tensorflow as tf

# Define a matrix tensor
matrix_tensor = tf.constant([[1, 2], [3, 4]])
print(matrix_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Define a ones tensor
ones_tensor = tf.ones_like(matrix_tensor)
print(ones_tensor)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [ ]:
# Element-wise addition
tensor_add = tf.add(matrix_tensor, ones_tensor)
print(tensor_add)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix multiplication (dot product)
matrix_mult = tf.matmul(matrix_tensor, matrix_tensor)
print(matrix_mult)

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [ ]:
# Reshape a tensor
#changing shape of matrix_tensor to [4, 1]
reshaped_tensor = tf.reshape(matrix_tensor, [4, 1])
print(reshaped_tensor)

tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


In [ ]:
# Transpose a tensor
# flip rows and columns of matrix_tensor
transpose_tensor = tf.transpose(matrix_tensor)
print(transpose_tensor)

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
#Accessing Tensor Elements
vector_tensor = tf.constant([1, 2, 3, 4])
print(vector_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
# Accessing the first element of a vector
first_element = vector_tensor[0]
print(first_element)

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# Define a matrix tensor
matrix_tensor = tf.constant([[1, 2], [3, 4]])
print(matrix_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Slicing a tensor
matrix_slice = matrix_tensor[:1, :]
print(matrix_slice)

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
